# Generated by Django 4.2.9 on 2024-03-08 15:05
from django.contrib.auth.models import User
from django.db import migrations

from users.models import Profile


def create_profile_objects(apps, schema_editor):
    for user in User.objects.all():
        if not hasattr(user, 'profile'):
            Profile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    ]
