# Generated by Django 4.2.10 on 2024-03-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_alter_movie_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='added_by',
        ),
    ]
